version: '3' 

services:
  sql_server:
    container_name: catalog-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=aJBuS&8Q^bJ5
    ports:
      - 6433:1433